# Generated by Django 3.2.9 on 2022-05-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rev_name',
            new_name='reviewer_name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_answer',
            new_name='reviewer_response',
        ),
    ]
