# Generated by Django 3.2.9 on 2022-05-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220526_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_price_currency',
            new_name='price_currency',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_response',
            new_name='response',
        ),
    ]
