# Generated by Django 3.2.9 on 2022-05-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220528_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to=None, verbose_name=''),
        ),
    ]
