# Generated by Django 3.2.9 on 2022-06-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to='browse-img/', verbose_name=''),
        ),
    ]
